name: ars_sms_retriever
description: Flutter plugin for retrieving OTP code sent in sms automatically and without getting SMS permission in Android.
version: 1.0.2
author: Ali Raghebi <aliraghebiii@gmail.com>
homepage: https://github.com/arsamme/flutter-sms-retriever

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.arsam.sms_retriever
        pluginClass: SmsRetrieverPlugin